# supabase/config.toml

project_id = "rigbiqjmszdlacjdkhep"

[functions.exchange-code-for-tokens]

[functions.get-google-config]

[functions.get-webhook-url]

[functions.google-token-exchange]

[functions.refresh-token]

[functions.send_webhook_to_make]

[functions.test-auth]

[functions.bright-action]
