# .github/workflows/supabase-functions.yml
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Function get-google-config
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy get-google-config --project-ref rigbiqjmszdlacjdkhep --no-verify-jwt

      - name: Deploy Edge Function exchange-code-for-tokens
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy exchange-code-for-tokens --project-ref rigbiqjmszdlacjdkhep --no-verify-jwt
