# .github/workflows/supabase-functions.yml
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main # main 브랜치에 변경사항이 생길 때만 실행
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Function get-google-config
        run: |
          supabase functions deploy get-google-config --project-ref rigbiqjmszdlacjdkhep
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Function exchange-code-for-tokens
        run: |
          supabase functions deploy exchange-code-for-tokens --project-ref rigbiqjmszdlacjdkhep
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
